#!/bin/bash

# Bootstrap the first pull from github.
# cd /home/ec2-user
# git clone https://github.com/Tomella/elvis-finder.git
# cd elvis-finder
# bower install

# Should be home already but make sure.
cd /home/ec2-user/elvis-finder

# Update code base
git pull
bower update

# Copy static content to Apache. We need a virtual domain registered. See the comment block below for more context.
if [ ! -d /var/www/metadata ]; then
  sudo mkdir -p /var/www/metadata
fi
sudo cp -rf dist/* /var/www/metadata

## Consider these behaviours for future capability like node services
# We used to update any proxies that might have changed here but it became unweildly so
# we moved this into an aggregated Apache configuration projet
# https://github.com/Tomella/apache-configuration

